from graph import Graph
def create_graph(g       )         :
    v2 = g.create_node(2)
    g
    g
    g.create_node(5)
    v6 = g.create_node(6)
    g.create_node(7)
    v8 = g.create_node(8)
    g.create_node(9)
    v10 = g.create_node(10)
    g.create_node(11)
    g.create_node(12)
    v13 = g.create_node(13)
    g.create_node(14)
    v15 = g.create_node(15)
    g.create_node(16)
    g.create_node(17)
    g.create_node(18)
    g.create_node(19)
    g.create_node(20)
    g.create_node(21)
    g.create_node(22)
    v23 = g.create_node(23)
    g.create_node(24)
    g.create_node(25)
    g.create_node(26)
    g.create_node(27)
    v28 = g.create_node(28)
    g.create_node(29)
    g.create_node(30)
    g.create_node(31)
    v32 = g.create_node(32)
    g.create_node(33)
    g.create_node(34)
    g.create_node(35)
    g.create_node(44)
    g.create_node(45)
    v46 = g.create_node(46)
    g
    g
    g.create_node(49)
    v53 = g.create_node(53)
    g.create_node(54)
    g.create_node(55)
    g.create_node(56)
    g.create_node(57)
    g.create_node(58)
    g.create_node(59)
    v60 = g.create_node(60)
    g.create_node(61)
    v65 = g.create_node(65)
    g.create_node(66)
    v67 = g.create_node(67)
    g.create_node(73)
    g.create_node(74)
    g.create_node(75)
    g.create_node(76)
    v77 = g.create_node(77)
    g.create_node(78)
    g.create_node(79)
    g.create_node(80)
    g.create_node(81)
    g.create_node(82)
    g.create_node(83)
    v89 = g.create_node(89)
    v92 = g.create_node(92)
    v94 = g.create_node(94)
    v96 = g.create_node(96)
    v99 = g.create_node(99)
    v100 = g.create_node(100)
    g
    g
    g
    g.create_unweighted_edge(v10, v28)
    g.create_unweighted_edge(v10, v28)
    g
    g.create_unweighted_edge(v8, v13)
    g.create_unweighted_edge(v53, v60)
    g.create_unweighted_edge(v53, v60)
    g
    g.create_unweighted_edge(v32, v89)
    g.create_unweighted_edge(v32, v89)
    g.create_unweighted_edge(v2, v32)
    g.create_unweighted_edge(v2, v32)
    g.create_unweighted_edge(v8, v92)
    g.create_unweighted_edge(v6, v32)
    g.create_unweighted_edge(v65, v89)
    g.create_unweighted_edge(v89, v96)
    g.create_unweighted_edge(v89, v96)
    g.create_unweighted_edge(v89, v96)
    g.create_unweighted_edge(v8, v89)
    g.create_unweighted_edge(v8, v89)
    g.create_unweighted_edge(v8, v89)
    g.create_unweighted_edge(v8, v32)
    return g
